services:
  api:
    image: ghcr.io/pi-trailblazer/ml_api:${TAG:-latest}
    build:
      context: ML_API
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    environment:
      - ENV=production
    volumes:
      - ./ML_API:/app
    restart: unless-stopped

  proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/locations.conf:/etc/nginx/conf.d/locations.conf:ro
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    depends_on:
      - api